/**
 * ESP32 secrets file
 * 
 * Contains information required to connect to WiFi and in-turn, AWS IoT
 * 
 * Authors: Vipul Deshpande, Jaime Burbano
 */


/*
  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
  Permission is hereby granted, free of charge, to any person obtaining a copy of this
  software and associated documentation files (the "Software"), to deal in the Software
  without restriction, including without limitation the rights to use, copy, modify,
  merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
  permit persons to whom the Software is furnished to do so.
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
  INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
  PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


#include <pgmspace.h>

#define SECRET
#define THINGNAME "Ulmitate killing machine"

const char WIFI_SSID[] = "Redmis";
const char WIFI_PASSWORD[] = "demon111";
const char AWS_IOT_ENDPOINT[] = "a87tb7ns56j1b-ats.iot.us-east-2.amazonaws.com";

/* Amazon Root CA 1 */
static const char AWS_CERT_CA[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----
)EOF";

/* Device Certificate */
static const char AWS_CERT_CRT[] PROGMEM = R"KEY(
-----BEGIN CERTIFICATE-----
MIIDWTCCAkGgAwIBAgIUd8yRAN94bmD6nrvV7vF768qTiBkwDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIxMTAzMTE2MTkz
NloXDTQ5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTQVdTIElvVCBDZXJ0aWZpY2F0
ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANQrmQFuNsid8luD9ZQj
2GDr4DJooiXOy/zzBt1DgGgUPMb79f9YebrKW+nuGaDD5vhJkOJytv/zUGV6fauP
/RoE/ztJiQb9PFNT5wgbQ2NTNS+Zmxt+9oTorWwVqlRiCuPlNqCUwVo0Cme4TqUM
HhtW37yozdnBn1FQxR6F9156L6EKLI72eZsL+j/esGxKGLXOY20cCDW78TrxRMhE
dUS5X2r0Op2g2oHXasSi9x9DHYvQ39huiMyAmt6Xf7iWR3khLgGyNI3zlOZRRpIx
sY/uv9Ft99X5KQ04nvUbjwePFAExcdPhw7Mv/RXGJJPQOvTnP60lcqK0xVXBFFyO
DTcCAwEAAaNgMF4wHwYDVR0jBBgwFoAUSul9HyX2Ul/kJv6FHZz0lPtcYQcwHQYD
VR0OBBYEFCIgG+sxeSRYbTPd5WT7Kmifn66+MAwGA1UdEwEB/wQCMAAwDgYDVR0P
AQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQCcr4MHirWiWQS2dPqEHI7zWA6W
95YB+vltShQhJifGbmxcSWFBvXM3zcdanxmzl5IkRR6S3pqSwPhk7pU4pJqbZu+i
JL4vPaO37YpI+S46CFNUloefKQD+yONqBtReJmMf3ebjagIacmpgnLxokZvby2XC
1bLVIeEp1aioUD5u/AG/+KruAXb6DMV+UiPgbzX5NiJLZCZccLGTan6KC74jh8u8
arMAfNFzuKZepWyKXyVKN5kmq6NOsAIE9fr+iMBKLboS40mhfUQ9Te9NR6klxhvS
NdVxEZf3UA2NGp/uFwtXqmHT5ULTU4u18nEiNPW3SjJJDSDr9CvbNQCiMEHR
-----END CERTIFICATE-----
)KEY";

/* Device Private Key */
static const char AWS_CERT_PRIVATE[] PROGMEM = R"KEY(
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEA1CuZAW42yJ3yW4P1lCPYYOvgMmiiJc7L/PMG3UOAaBQ8xvv1
/1h5uspb6e4ZoMPm+EmQ4nK2//NQZXp9q4/9GgT/O0mJBv08U1PnCBtDY1M1L5mb
G372hOitbBWqVGIK4+U2oJTBWjQKZ7hOpQweG1bfvKjN2cGfUVDFHoX3XnovoQos
jvZ5mwv6P96wbEoYtc5jbRwINbvxOvFEyER1RLlfavQ6naDagddqxKL3H0Mdi9Df
2G6IzICa3pd/uJZHeSEuAbI0jfOU5lFGkjGxj+6/0W331fkpDTie9RuPB48UATFx
0+HDsy/9FcYkk9A69Oc/rSVyorTFVcEUXI4NNwIDAQABAoIBAQC+I8QfEBJwf3vu
n7e5ZtZHJZvqEPMfRtBwg6snJ5MvstM00CCJEVUmHKt6XTMCbA3VfLgm9/8gKYFn
L/rngUalxsyk6SWv6cniM1LcZPJjVPJZEiN65LEwMwUX0+KtdJ+l1Ii8KBOPLwwU
H4v7RXzFq3kerXitKWQJj4TX8d7Z/quEId4B9uNaDu0kTw3ZeBTowy5cRs6oZJ9b
ja8UqPPVcsEaeEKLU6Ff/SinLLviqlk001qrNJ9JQHXr/kbt0wN4j7ajNlUgeuf8
Hs0dw9nbcMAeAJ3VkOA/fr9ygDtrD7StIRgZcFOIzh0nfIEmu3PgjXVfN2WWHDsD
LnjEP0fBAoGBAPkMW6fHBRgNjC51bQr4bNe6AL73qhiOej4Ue7ZHI2Dn8X5X68XQ
zJP2HfshZdUE5Vm7tr4zfADFGuJiLFX0hjDLHVsuZ7hvF8IA2blclhDKRWAIE+jT
mIy2QK6O4gtbMyh40xH4SVXOJ4/jISzaMQCDv7O4zuSBB2ijgakkYz4PAoGBANoX
t9ZO9OWwf79LC2orvoFeLAFSFN9AGJs2BjRWTvL/oYuwbnKElgL8gExh4snZV0eS
4ohyuEmECszQOni2MYYFt5nDzejMgy58wcR+ZTbxqBGGknHN/Y3Hnwq9BKSGLhEa
DILbQyZaeAC6FzegzyVl1VByBkw81U0TtCE69OZZAoGAMUyF9C9MTdeYsTWjcTF9
8jIqpaLG8/d4MUPCvXFVioA/aKAk1tKfPIbSpnyU+NbwQ5QJ95qfaFOcH8YJOrad
vZjnZb5I39R14nxinPO77PTtSLYwor0IDIqjQSqdilvyQ4evWHZKpgaaBDyUu5kx
bAWoc/4YTllQSyFasE24q3cCgYB0/cwsNmbA4BFnOIaDCbxEAZRxkOqJaATLHgvt
/26Sg/bQzHAzFlSyfWkFkGzsAp8DUhQbRg79wMtaW0lCf9nJH0ACSDso6qxkP6Bi
G7uH4dJatGnSisG9UJxMUmEvMJt9qQ+VErHO3TEKksjpmmYElb/8S259bxStKCi0
ur+s4QKBgCb5M+p3tm5eB3t4pxarxckErD0WujQjKxR3kWFoTdRIXID9w8D+5fis
XjCHtYv1WQrDAX87XwZOo+KGQTW1j2YRMkL/WMm/GQQosMcTARIbXkDqwJxtvaoO
OhizNB84zvAsmerM2Ed4MT8pKc7OC5KxeGnXRbLQ3eOn41cZXGEY
-----END RSA PRIVATE KEY-----
)KEY";